# Visualizamos los datos

## Rutas e imports

In [1]:
from pathlib import Path
import pandas as pd
from pyspark.sql.functions import col, to_date
from IPython.display import display

PROJECT_ROOT = Path("/home/math2data/nyc-mobility-lakehouse")

LANDING_DIR = PROJECT_ROOT / "data" / "landing"
BRONZE_DIR = PROJECT_ROOT / "data" / "bronze" / "yellow_taxi_trips"

print(PROJECT_ROOT)
print(LANDING_DIR.exists())
print(BRONZE_DIR.exists())

/home/math2data/nyc-mobility-lakehouse
True
True

### Cargamos los parquets brutos

In [2]:
landing_files = sorted(LANDING_DIR.glob("yellow_tripdata_2023-*.parquet"))
landing_files

[PosixPath('/home/math2data/nyc-mobility-lakehouse/data/landing/yellow_tripdata_2023-01.parquet'),
 PosixPath('/home/math2data/nyc-mobility-lakehouse/data/landing/yellow_tripdata_2023-02.parquet'),
 PosixPath('/home/math2data/nyc-mobility-lakehouse/data/landing/yellow_tripdata_2023-03.parquet')]

### Visualizamos los parquets en bruto

In [345]:
for i, file in enumerate(landing_files, start=1):
    raw_df = pd.read_parquet(file)
    print(f"Visualizamos una muestra del Parquet {i}: {file.name}")
    display(raw_df.sample(5, random_state=42))
    print(f"Shape: {raw_df.shape}")

Visualizamos una muestra del Parquet 1: yellow_tripdata_2023-01.parquet

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
2790731,2,2023-01-29 17:52:02,2023-01-29 17:56:43,1.0,1.17,1.0,N,262,74,2,7.2,0.0,0.5,0.00,0.0,1.0,11.20,2.5,0.0
666153,1,2023-01-08 15:57:24,2023-01-08 16:02:47,1.0,0.90,1.0,N,229,237,2,6.5,2.5,0.5,0.00,0.0,1.0,10.50,2.5,0.0
1985683,2,2023-01-21 19:38:01,2023-01-21 19:45:02,1.0,0.95,1.0,N,45,261,1,7.9,0.0,0.5,2.38,0.0,1.0,14.28,2.5,0.0
2154231,2,2023-01-23 16:07:31,2023-01-23 16:26:46,5.0,0.88,1.0,N,237,141,1,16.3,2.5,0.5,1.50,0.0,1.0,24.30,2.5,0.0
2493619,2,2023-01-26 21:21:08,2023-01-26 21:24:48,2.0,1.03,1.0,N,229,140,1,6.5,1.0,0.5,2.30,0.0,1.0,13.80,2.5,0.0

Shape: (3066766, 19)
Visualizamos una muestra del Parquet 2: yellow_tripdata_2023-02.parquet

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
1288541,2,2023-02-13 17:11:02,2023-02-13 17:16:46,1.0,0.94,1.0,N,141,262,1,7.9,2.5,0.5,2.88,0.00,1.0,17.28,2.5,0.00
482949,2,2023-02-05 18:39:05,2023-02-05 19:10:29,2.0,10.39,1.0,N,138,61,1,45.0,5.0,0.5,10.00,0.00,1.0,62.75,0.0,1.25
2037515,2,2023-02-21 10:15:06,2023-02-21 10:51:25,1.0,10.26,1.0,N,138,163,1,47.8,5.0,0.5,3.00,6.55,1.0,67.60,2.5,1.25
2411597,2,2023-02-24 18:40:20,2023-02-24 18:55:07,1.0,1.53,1.0,N,234,230,1,14.2,2.5,0.5,4.14,0.00,1.0,24.84,2.5,0.00
1045088,2,2023-02-11 08:55:21,2023-02-11 09:16:10,1.0,16.71,2.0,N,137,132,1,70.0,0.0,0.5,24.16,6.55,1.0,104.71,2.5,0.00

Shape: (2913955, 19)
Visualizamos una muestra del Parquet 3: yellow_tripdata_2023-03.parquet

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
2904679,1,2023-03-28 11:58:18,2023-03-28 12:02:00,1.0,0.30,1.0,N,236,236,2,5.1,2.5,0.5,0.00,0.0,1.0,9.10,2.5,0.0
3144343,2,2023-03-30 15:59:15,2023-03-30 16:11:14,1.0,0.56,1.0,N,161,161,1,11.4,0.0,0.5,3.08,0.0,1.0,18.48,2.5,0.0
1278494,2,2023-03-12 18:11:38,2023-03-12 18:17:31,5.0,1.07,1.0,N,151,239,1,7.9,0.0,0.5,2.38,0.0,1.0,14.28,2.5,0.0
2578212,1,2023-03-24 23:27:20,2023-03-24 23:36:04,1.0,1.10,1.0,N,4,211,1,7.9,3.5,0.5,2.60,0.0,1.0,15.50,2.5,0.0
3345592,1,2023-03-11 12:19:06,2023-03-11 12:27:00,NaN,1.50,NaN,NaN,236,238,0,10.0,0.0,0.5,0.00,0.0,1.0,14.00,NaN,NaN

Shape: (3403766, 19)

In [346]:
raw_df.notna().sum()[raw_df.notna().sum() > 0]

VendorID                 3403766
tpep_pickup_datetime     3403766
tpep_dropoff_datetime    3403766
passenger_count          3316147
trip_distance            3403766
RatecodeID               3316147
store_and_fwd_flag       3316147
PULocationID             3403766
DOLocationID             3403766
payment_type             3403766
fare_amount              3403766
extra                    3403766
mta_tax                  3403766
tip_amount               3403766
tolls_amount             3403766
improvement_surcharge    3403766
total_amount             3403766
congestion_surcharge     3316147
Airport_fee              3316147
dtype: int64

In [347]:
dtypes_por_archivo = {}

for file in landing_files:
    raw_df = pd.read_parquet(file)
    dtypes_por_archivo[file.name] = raw_df.dtypes

In [348]:
# Convertimos a DataFrame: filas = columnas, columnas = archivos
comparativa_dtypes = pd.DataFrame(dtypes_por_archivo)

# Columnas donde no todos los archivos tienen el mismo dtype
dtypes_diferentes = comparativa_dtypes[
    comparativa_dtypes.nunique(axis=1, dropna=False) > 1
]

dtypes_diferentes

if dtypes_diferentes.empty:
    print("Todos los archivos tienen las mismas columnas con los mismos dtypes.")
else:
    print("Hay diferencias de dtypes o columnas entre archivos:")
    display(dtypes_diferentes)

Hay diferencias de dtypes o columnas entre archivos:

,yellow_tripdata_2023-01.parquet,yellow_tripdata_2023-02.parquet,yellow_tripdata_2023-03.parquet
Airport_fee,NaN,float64,float64
DOLocationID,int64,int32,int32
PULocationID,int64,int32,int32
VendorID,int64,int32,int32
airport_fee,float64,NaN,NaN

In [349]:
#En caso de que no haya los mismos tipos averiguamos donde se está produciendo el fallo
for columna, fila in dtypes_diferentes.iterrows():
    print(f"\nColumna con diferencias: {columna}")

    for archivo, dtype in fila.items():
        print(f"  {archivo}: {dtype}")

Columna con diferencias: Airport_fee
  yellow_tripdata_2023-01.parquet: nan
  yellow_tripdata_2023-02.parquet: float64
  yellow_tripdata_2023-03.parquet: float64

Columna con diferencias: DOLocationID
  yellow_tripdata_2023-01.parquet: int64
  yellow_tripdata_2023-02.parquet: int32
  yellow_tripdata_2023-03.parquet: int32

Columna con diferencias: PULocationID
  yellow_tripdata_2023-01.parquet: int64
  yellow_tripdata_2023-02.parquet: int32
  yellow_tripdata_2023-03.parquet: int32

Columna con diferencias: VendorID
  yellow_tripdata_2023-01.parquet: int64
  yellow_tripdata_2023-02.parquet: int32
  yellow_tripdata_2023-03.parquet: int32

Columna con diferencias: airport_fee
  yellow_tripdata_2023-01.parquet: float64
  yellow_tripdata_2023-02.parquet: nan
  yellow_tripdata_2023-03.parquet: nan

## Visualizamos usando Spark

In [4]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("View Landing and Bronze")
    .config("spark.driver.memory", "4g")
    .config("spark.jars.packages", "io.delta:delta-spark_2.12:3.1.0")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("ERROR")

26/05/18 15:45:35 WARN Utils: Your hostname, DESKTOP-VAU4PKR resolves to a loopback address: 127.0.1.1; using 172.21.253.134 instead (on interface eth0)
26/05/18 15:45:35 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

:: loading settings :: url = jar:file:/home/math2data/nyc-mobility-lakehouse/venv/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/math2data/.ivy2/cache
The jars for the packages stored in: /home/math2data/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-8984a53a-31a6-4a01-bdfd-015735b1476f;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.1.0 in central
	found io.delta#delta-storage;3.1.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 174ms :: artifacts dl 9ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.1.0 from central in [default]
	io.delta#delta-storage;3.1.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-8984a53a-31a6-4a01-bdfd-015735b1476f
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/8ms)
26/05/18 15:45:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [8]:
bronze_df = spark.read.format("delta").load(str(BRONZE_DIR))

In [9]:
bronze_df.limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,source_file,ingestion_timestamp,service_type,year,month,batch_id
0,2.0,2023-03-01 00:06:43,2023-03-01 00:16:43,1.0,0.00,1.0,N,238.0,42.0,2.0,...,1.0,11.10,0.0,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-18 15:18:29.125774,yellow,2023,03,9e328eaa-3654-4d4d-95fc-f032292938ca
1,2.0,2023-03-01 00:08:25,2023-03-01 00:39:30,2.0,12.40,1.0,N,138.0,231.0,1.0,...,1.0,76.49,2.5,1.25,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-18 15:18:29.125774,yellow,2023,03,9e328eaa-3654-4d4d-95fc-f032292938ca
2,1.0,2023-03-01 00:15:04,2023-03-01 00:29:26,0.0,3.30,1.0,N,140.0,186.0,1.0,...,1.0,28.05,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-18 15:18:29.125774,yellow,2023,03,9e328eaa-3654-4d4d-95fc-f032292938ca
3,1.0,2023-03-01 00:49:37,2023-03-01 01:01:05,1.0,2.90,1.0,N,140.0,43.0,1.0,...,1.0,24.70,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-18 15:18:29.125774,yellow,2023,03,9e328eaa-3654-4d4d-95fc-f032292938ca
4,2.0,2023-03-01 00:08:04,2023-03-01 00:11:06,1.0,1.23,1.0,N,79.0,137.0,1.0,...,1.0,14.64,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-18 15:18:29.125774,yellow,2023,03,9e328eaa-3654-4d4d-95fc-f032292938ca

In [353]:
bronze_df.filter(
    (col("year") == "2023") & (col("month") == "01")
).limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,source_file,ingestion_timestamp,service_type,year,month,batch_id
0,2.0,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161.0,141.0,2.0,...,1.0,14.30,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:30:34.135336,yellow,2023,01,fe98c3ea-2294-4cd2-8513-bd8b99a08188
1,2.0,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43.0,237.0,1.0,...,1.0,16.90,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:30:34.135336,yellow,2023,01,fe98c3ea-2294-4cd2-8513-bd8b99a08188
2,2.0,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48.0,238.0,1.0,...,1.0,34.90,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:30:34.135336,yellow,2023,01,fe98c3ea-2294-4cd2-8513-bd8b99a08188
3,1.0,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138.0,7.0,1.0,...,1.0,20.85,0.0,1.25,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:30:34.135336,yellow,2023,01,fe98c3ea-2294-4cd2-8513-bd8b99a08188
4,2.0,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107.0,79.0,1.0,...,1.0,19.68,2.5,0.00,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:30:34.135336,yellow,2023,01,fe98c3ea-2294-4cd2-8513-bd8b99a08188

In [354]:
bronze_df.printSchema()

root
 |-- VendorID: double (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: double (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: double (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: double (nullable = true)
 |-- DOLocationID: double (nullable = true)
 |-- payment_type: double (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- source_file: string (nullable = true)
 |-- ingestion_timestamp: timestamp (nullable = true)
 |-- service_type: string (nullable = true)
 |-- year: string (nullable = true)
 |-- month: string (nullable = true)
 |-- batch_id: string (nullable = true)

In [355]:
bronze_df.groupBy("year", "month").count().orderBy("year", "month").toPandas()

   year month    count
0  2023    01  3066766
1  2023    02  2913955
2  2023    03  3403766

In [356]:
raw_columns = set(raw_df.columns)
bronze_columns = set(bronze_df.columns)

{
    "solo_en_raw": sorted(raw_columns - bronze_columns),
    
    "solo_en_bronze": sorted(bronze_columns - raw_columns),
    
    "comunes": sorted(raw_columns & bronze_columns)
}

{'solo_en_raw': ['Airport_fee'],
 'solo_en_bronze': ['airport_fee',
  'batch_id',
  'ingestion_timestamp',
  'month',
  'service_type',
  'source_file',
  'year'],
 'comunes': ['DOLocationID',
  'PULocationID',
  'RatecodeID',
  'VendorID',
  'congestion_surcharge',
  'extra',
  'fare_amount',
  'improvement_surcharge',
  'mta_tax',
  'passenger_count',
  'payment_type',
  'store_and_fwd_flag',
  'tip_amount',
  'tolls_amount',
  'total_amount',
  'tpep_dropoff_datetime',
  'tpep_pickup_datetime',
  'trip_distance']}

In [357]:
bronze_df.select(
    "source_file",
    "ingestion_timestamp",
    "service_type",
    "year",
    "month",
    "batch_id"
).limit(5).toPandas()

,source_file,ingestion_timestamp,service_type,year,month,batch_id
0,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:31:06.625703,yellow,2023,02,478407f0-4c96-4f2a-8a0c-d751e7413251
1,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:31:06.625703,yellow,2023,02,478407f0-4c96-4f2a-8a0c-d751e7413251
2,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:31:06.625703,yellow,2023,02,478407f0-4c96-4f2a-8a0c-d751e7413251
3,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:31:06.625703,yellow,2023,02,478407f0-4c96-4f2a-8a0c-d751e7413251
4,file:///home/math2data/nyc-mobility-lakehouse/...,2026-05-06 14:31:06.625703,yellow,2023,02,478407f0-4c96-4f2a-8a0c-d751e7413251

In [358]:
from pyspark.sql import functions as F


raw_columns = set(raw_df.columns)
bronze_columns = set(bronze_df.columns)

comparativa_columnas = []

for colm in sorted(raw_columns | bronze_columns):
    comparativa_columnas.append({
        "columna": colm,
        "en_raw": colm in raw_columns,
        "en_bronze": colm in bronze_columns,
        "estado": (
            "común" if colm in raw_columns and colm in bronze_columns
            else "solo_en_raw" if colm in raw_columns
            else "solo_en_bronze"
        )
    })

comparativa_df = spark.createDataFrame(comparativa_columnas)

comparativa_df.orderBy("estado", "columna").toPandas()

                  columna  en_bronze  en_raw          estado
0            DOLocationID       True    True           común
1            PULocationID       True    True           común
2              RatecodeID       True    True           común
3                VendorID       True    True           común
4    congestion_surcharge       True    True           común
5                   extra       True    True           común
6             fare_amount       True    True           común
7   improvement_surcharge       True    True           común
8                 mta_tax       True    True           común
9         passenger_count       True    True           común
10           payment_type       True    True           común
11     store_and_fwd_flag       True    True           común
12             tip_amount       True    True           común
13           tolls_amount       True    True           común
14           total_amount       True    True           común
15  tpep_dropoff_datetime       True    True           común
16   tpep_pickup_datetime       True    True           común
17          trip_distance       True    True           común
18            airport_fee       True   False  solo_en_bronze
19               batch_id       True   False  solo_en_bronze
20    ingestion_timestamp       True   False  solo_en_bronze
21                  month       True   False  solo_en_bronze
22           service_type       True   False  solo_en_bronze
23            source_file       True   False  solo_en_bronze
24                   year       True   False  solo_en_bronze
25            Airport_fee      False    True     solo_en_raw

In [359]:
comparativa_df.filter(
    F.col("estado") != "común"
).orderBy("estado", "columna").toPandas()

               columna  en_bronze  en_raw          estado
0          airport_fee       True   False  solo_en_bronze
1             batch_id       True   False  solo_en_bronze
2  ingestion_timestamp       True   False  solo_en_bronze
3                month       True   False  solo_en_bronze
4         service_type       True   False  solo_en_bronze
5          source_file       True   False  solo_en_bronze
6                 year       True   False  solo_en_bronze
7          Airport_fee      False    True     solo_en_raw

In [360]:
raw_lower = {c.lower(): c for c in raw_df.columns}
bronze_lower = {c.lower(): c for c in bronze_df.columns}

for col_lower in sorted(set(raw_lower) & set(bronze_lower)):
    if raw_lower[col_lower] != bronze_lower[col_lower]:
        print(
            f"Posible misma columna con distinto nombre: "
            f"raw='{raw_lower[col_lower]}', bronze='{bronze_lower[col_lower]}'"
        )

Posible misma columna con distinto nombre: raw='Airport_fee', bronze='airport_fee'

In [361]:
dtypes_por_archivo_spark = {}

for file in landing_files:
    df_spark = spark.read.parquet(str(file))
    
    dtypes_por_archivo_spark[file.name] = {
        col_name: dtype
        for col_name, dtype in df_spark.dtypes
    }

comparativa_dtypes_spark = pd.DataFrame(dtypes_por_archivo_spark)

dtypes_diferentes_spark = comparativa_dtypes_spark[
    comparativa_dtypes_spark.nunique(axis=1, dropna=False) > 1
]

if dtypes_diferentes_spark.empty:
    print("Todos los archivos tienen las mismas columnas con los mismos dtypes.")
else:
    print("Hay diferencias de dtypes o columnas entre archivos:")
    display(dtypes_diferentes_spark)

Hay diferencias de dtypes o columnas entre archivos:

,yellow_tripdata_2023-01.parquet,yellow_tripdata_2023-02.parquet,yellow_tripdata_2023-03.parquet
VendorID,bigint,int,int
passenger_count,double,bigint,bigint
RatecodeID,double,bigint,bigint
PULocationID,bigint,int,int
DOLocationID,bigint,int,int
airport_fee,double,NaN,NaN
Airport_fee,NaN,double,double

In [362]:
spark.stop()